-- MySQL Script generated by MySQL Workbench
-- Tue Jul  1 13:51:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Case_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Case_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Case_table` (
  `Case_id` INT NOT NULL,
  `Case_title4` VARCHAR(45) NULL,
  `Crime_id` INT NULL,
  `Officer_id` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Court_date` DATE NULL,
  `Remarks` TEXT NULL,
  PRIMARY KEY (`Case_id`),
  CONSTRAINT `Crime_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Crime_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Officer_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Officer_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Crime_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Crime_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Crime_table` (
  `Crime_id` INT NOT NULL,
  `Crime type` VARCHAR(45) NULL,
  `Date_committed` DATE NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Seveirty_level` VARCHAR(45) NULL,
  PRIMARY KEY (`Crime_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Criminal_Crime_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Criminal_Crime_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Criminal_Crime_table` (
  `Criminal_id` INT NOT NULL,
  `Crime_id` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  `Date_arrested` DATE NULL,
  CONSTRAINT `Criminal_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Criminal_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Crime_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Crime_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Criminal_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Criminal_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Criminal_table` (
  `Criminal_id` INT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Alias` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `DOB` DATE NULL,
  `Nationality` VARCHAR(45) NULL,
  `Photo` VARCHAR(45) NULL DEFAULT 'Blob/URL',
  `Address` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`Criminal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evidence_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evidence_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evidence_table` (
  `Evidence_id` INT NOT NULL,
  `Case_id` INT NULL,
  `Type` VARCHAR(45) NULL,
  `Description` TEXT NULL,
  `Collected_date` DATE NULL,
  `Location_found` VARCHAR(45) NULL,
  PRIMARY KEY (`Evidence_id`),
  CONSTRAINT `Case_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Case_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login_table\`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Login_table\` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Login_table\` (
  `User_id` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Officer_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Officer_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Officer_table` (
  `Officer_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Rank` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(45) NOT NULL,
  `Station` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Officer_id`),
  UNIQUE INDEX `Contact_UNIQUE` (`Contact` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Victim_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Victim_table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Victim_table` (
  `Victim_id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(45) NOT NULL,
  `Crime_id` INT NULL,
  `Status` VARCHAR(45) NULL,
  `Statement` TEXT NULL,
  PRIMARY KEY (`Victim_id`),
  UNIQUE INDEX `Contact_UNIQUE` (`Contact` ASC) VISIBLE,
  CONSTRAINT `Crime_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Crime_table` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS Ankita Pattanaik;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Ankita Pattanaik' IDENTIFIED BY 'anku123';

GRANT ALL ON `mydb`.* TO 'Ankita Pattanaik';
GRANT SELECT ON TABLE `mydb`.* TO 'Ankita Pattanaik';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'Ankita Pattanaik';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'Ankita Pattanaik';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'Ankita Pattanaik';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
